name: Deploy to Hackshack
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 192.168.2.206
          username: garik
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/garik/projects/healthcheck
            git pull origin main
            pnpm install --omit=dev
            pnpm run build
            pm2 restart healthcheck
