name: Deploy to Hackshack
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy via Cloudflare Tunnel
        env:
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          cloudflared access ssh --hostname hackshack.garik.codes --id $CF_CLIENT_ID --secret $CF_CLIENT_SECRET --command "cd /home/garik/projects/healthcheck && git pull origin main && pnpm install --omit=dev && pnpm run build && pm2 reload healthcheck"
